### ISSUE TITLE
openairinterface5g - 5g_l2sim_tdd

### ISSUE THREAD

**Issue by echobom** [echobom/notes#6]
https://gitlab.eurecom.fr/oai/openairinterface5g/-/tree/develop/ci-scripts/yaml_files/5g_l2sim_tdd

**Comment by echobom** [comment]
```
sudo ifconfig lo: 127.0.0.2 netmask 255.0.0.0 up
```

**Comment by echobom** [comment]
```
$ cd ci-scripts/yaml_files/5g_l2sim_tdd
$ docker-compose up -d mysql oai-nrf oai-amf oai-smf oai-spgwu oai-ext-dn
```

**Comment by echobom** [comment]
```
$ docker-compose up -d oai-gnb
```

**Comment by echobom** [comment]
```
$ docker-compose up -d proxy oai-nr-ue0
```

**Comment by echobom** [comment]
In the `SMF` section, provide your own DNS IP address:

```yaml
            DEFAULT_DNS_IPV4_ADDRESS=172.21.3.100
```

In the `gNB` section, provide your docker-host primary IP address and interface name: in our case `172.21.16.128` and `eno1`.

```yaml
            GNB_NGA_IF_NAME: eno1
            GNB_NGA_IP_ADDRESS: 172.21.16.128
            GNB_NGU_IF_NAME: eno1
            GNB_NGU_IP_ADDRESS: 172.21.16.128
```

Same thing in the `nr-ue` section:

```yaml
            NR_UE_NFAPI_IF_NAME: eno1
```
